// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN4W47nDP6VuRlkpqrvZ5pQS7jbj6sKn4',
    appId: '1:747848108767:web:7c95a4344787a10c55776a',
    messagingSenderId: '747848108767',
    projectId: 'friendstory-5a190',
    authDomain: 'friendstory-5a190.firebaseapp.com',
    storageBucket: 'friendstory-5a190.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwliQVuxy2ppHga1wzzyqfyqRcZrhdfYg',
    appId: '1:747848108767:android:359f9f8c3dbe3a5455776a',
    messagingSenderId: '747848108767',
    projectId: 'friendstory-5a190',
    storageBucket: 'friendstory-5a190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ox_OIKKAaBg3Lbj7i0zioeKnIzK3lHs',
    appId: '1:747848108767:ios:0e3c5089735f195655776a',
    messagingSenderId: '747848108767',
    projectId: 'friendstory-5a190',
    storageBucket: 'friendstory-5a190.appspot.com',
    iosClientId: '747848108767-lfbt6ctdhkbjhkgkprvgj40vdn7k1ge6.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendStory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ox_OIKKAaBg3Lbj7i0zioeKnIzK3lHs',
    appId: '1:747848108767:ios:0e3c5089735f195655776a',
    messagingSenderId: '747848108767',
    projectId: 'friendstory-5a190',
    storageBucket: 'friendstory-5a190.appspot.com',
    iosClientId: '747848108767-lfbt6ctdhkbjhkgkprvgj40vdn7k1ge6.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendStory',
  );
}
